# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20170404_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email2',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
