# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170831_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
