# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 23:47
from __future__ import unicode_literals
import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    for row in Profile.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
