# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 23:47
from __future__ import unicode_literals
import uuid

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170513_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
