# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170501_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
