# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizevariant',
            name='product',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
    ]
