# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20170426_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('canceled', 'Cancelled')], default='Created', max_length=120),
        ),
    ]
