# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 19:41
from __future__ import unicode_literals
import uuid
from django.db import migrations

def gen_uuid(apps,schema_editor):
    Order = apps.get_model('checkout', 'Order')
    for row in Order.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20170512_2141'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
