# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20170512_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='use_as_billing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
