# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 12:34
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Order = apps.get_model('checkout', 'Order')
    for row in Order.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('checkout', '0008_order_slug'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
