# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20170614_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
