# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20170831_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='products.Product'),
            preserve_default=False,
        ),
    ]
