# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
    ]
