# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_total_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_qty',
        ),
    ]
