# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment Method'},
        ),
    ]
